### ISSUE TITLE
MainContainer issue with Sidebar as props

### ISSUE THREAD

**Issue by Reza-Rajabi** [Whatsupjs/prj666#13]
I am going to solve the issue with Sidebar which is currently commented out in MainContainer.
@Whatsupjs Could you please comment here in which page Sidebar is misformatted if I apply the changes I just mentioned?  I wanna make sure it will be well formated for all components.

**Comment by Whatsupjs** [comment]
both service list pages and all of user pages (profile, user service, user booking)

**Comment by Reza-Rajabi** [comment]
Fixed now.
